### ISSUE TITLE
HiveLayoutManager.VERTICAL 不是public的

### ISSUE THREAD

**Issue by octomato** [Chacojack/HiveLayoutManager#4]
new HiveLayoutManager(HiveLayoutManager.VERTICAL)，因为HiveLayoutManager.VERTICAL不是public的所以报错。

**Comment by octomato** [comment]
ps. 当然前提显示蜂巢的Activity是存放在包名与你的那个jack.hive 不一样时会出现这个报错。

**Comment by Chacojack** [comment]
谢谢提醒，已经改正。
